---
- name: install jdk on hosts 
  hosts:
    - 192.168.0.104
  become: true
  tasks:
    - name: installing using apt
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes
