---
# Please Refer to .md file before running this playbook for extra variables that needed to be passed for this playbook
- name: redeploy latest artifact to windows iis server
  hosts: win_server2
  vars:
    site_base_path: "C:\\Users\\ansible\\Downloads\\sites"
    artifact_dir: "{{ site_base_path }}\\{{ project_name }}\\artifacts"
    backup_dir: "{{ site_base_path }}\\{{ project_name }}\\backup"
    console_output_dir: "{{ site_base_path }}\\{{ project_name }}\\console-output"
    java_jdk_path: "C:\\jdk-25.0.2\\bin\\java.exe"
  tasks:
    - name: ensure all required directory exist
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ artifact_dir }}"
        - "{{ backup_dir }}"
        - "{{ console_output_dir }}"
    - name: find list of all artifacts of this project and store it is variable
      ansible.windows.win_find:
        paths: "{{ artifact_dir }}"
        patterns: "{{ project_name }}-*.jar"
      register: all_win_artifacts
    - name: Stop Failed service
      ansible.windows.win_service:
        name: "{{ project_name }}"
        state: stopped
    - name: Wait for server port to be open
      ansible.windows.win_wait_for:
        port: "{{ server_port }}"
        state: stopped
        timeout: 30
    - name: Fail if no rollback artifact available
      fail:
        msg: "Deployment failed and no previous artifact available for rollback"
      when: all_win_artifacts.matched < 2
    - name: Rollbacking to previous version of deployment as service
      community.windows.win_nssm:
        name: "{{ project_name }}"
        application: "{{ java_jdk_path }}"
        app_parameters_free_form: >-
          -jar "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[1].path }}" --server.port={{ server_port }} --spring.profiles.active={{ deploy_env }}
        app_directory: "{{ artifact_dir }}"
        stdout_file: "{{ console_output_dir }}\\{{ project_name }}.log"
        stderr_file: "{{ console_output_dir }}\\{{ project_name }}.log"
        extra_parameters:
          AppRotateFiles: 1
          AppRotateOnline: 1
          AppRotateBytes: 10485760
        state: present
    - name: Starting Rollback Service
      ansible.windows.win_service:
        name: "{{ project_name }}"
        state: started
    - name: remove failed artifact from artifacts
      ansible.windows.win_file:
        path: "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[0].path }}"
        state: absent
    - name: Health Check
      ansible.windows.win_uri:
        url: "{{ site_url }}"
        status_code: "{{ expected_status_code | default(200) }}"
      register: health_check
      retries: 3
      delay: 5
      until: health_check.status_code == expected_status_code | int
      ignore_errors: true
    - name: Remove old artifacts if more than 3 is there
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[3:] }}"
      when: all_win_artifacts.matched > 3
