---
# Please Refer to .md file before running this playbook for extra variables that needed to be passed for this playbook
- name: redeploy latest artifact to windows iis server
  hosts: win_hostkp
  vars:
    site_base_path: "C:\\Users\\ansible\\Downloads\\sites"
    artifact_dir: "{{ site_base_path }}\\{{ project_name }}\\artifacts"
  tasks:
    - name: ensure all required directory exist
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ artifact_dir }}"
    - name: fetch latest artifact using url and store response
      ansible.windows.win_uri:
        url: "{{ nexus_url }}"
        method: HEAD
      register: response
    - name: setting artifact name from url
      set_fact: 
        artifact_name: "{{ response.response_uri | basename }} " 
    - name: download latest artifact using response variable
      ansible.windows.win_get_url:
        url: "{{ response.response_uri }}"
        dest: "{{ artifact_dir }}\\{{ artifact_name }}"
    - name: find list of all artifacts of this project and store it is variable
      ansible.windows.win_find:
        paths: "{{ artifact_dir }}"
        patterns: "{{ project_name }}-*.jar"
      register: all_win_artifacts
    - name: deployment with rollback
      block:
        - name: Run a JAR file on Windows
          ansible.windows.win_command: java -jar "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[0].path }}"
          args:
            chdir: "{{ artifact_dir }}" 
        - name: waiting 10sec for website to start properly
          pause:
            seconds: 10
        - name: check site health
          ansible.windows.win_uri:
            url: "{{ site_url }}"
            status_code: "{{ expected_status_code || default(200) }}"
      rescue:
        - name: Wait until server port is offline but try every 10 seconds
          ansible.windows.win_wait_for:
            port: "{{ server_port }}"
            state: absent
            sleep: 10
        - name: unzip latest at root
          community.windows.win_unzip:
            src: "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[1].path }}"
            dest: "{{ deploy_root }}"
            remote_src: true
        - name: remove failed artifact from artifacts
          ansible.windows.win_file:
            path: "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[0].path }}"
            state: absent
    - name: Remove old artifacts if more than 2 is there
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ (all_win_artifacts.files | sort(attribute='lastwritetime') | reverse)[2:] }}"
      when: all_win_artifacts.matched > 2        
